language: node_js
node_js:
  - "10.15.3"
cache: npm
script:
  - npm run build
  - npm run coveralls
  - jest --coverage --coverageReporters=text-lcov | coveralls
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
